# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!


# Priority enum for Todo items
enum Priority {
	LOW
	MEDIUM
	HIGH
}

# Status enum for Todo workflow
enum Status {
	TODO
 	INPROGRESS
 	VERIFY
 	COMPLETE
}

# The Todo model used by the application. Adjust fields as needed.
type Todo @model @auth(rules: [{ allow: public }]) {
	id: ID!
	title: String!
	description: String
	status: Status!
	dueDate: AWSDateTime
	priority: Priority
	tags: [String]
	createdAt: AWSDateTime
	updatedAt: AWSDateTime
}

